name: Winery Cinema Campaign
favicon: null
layout_spectrum: 0.6437740372493863
typography_spectrum: 0.6998011614196002
title: Turnkey Cinematic Marketing for Wineries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.599026836687699
  lightness: 0.9830940023530275
  saturation: 0.23019215604290366
  rhythmicContrast: 0.33192568831145763
purpose: []
